# Generated by Django 5.0.1 on 2024-01-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='item',
        ),
    ]
